spring:
  datasource:
    url: jdbc:postgresql://ep-orange-water-78030098-pooler.us-east-1.postgres.vercel-storage.com/verceldb
    username: default
    password: aCVFp1fISX4M
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true